---
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse   = TRUE,
  warning    = FALSE,
  message    = FALSE,
  comment    = "#>",
  fig.path   = "man/figures/",
  fig.retina = 3
)
```

# Welcome to our survey!


Thank you for participating in this survey, which is part of a research effort by Lund University. For this survey, we will ask you about your preferences for different types of housing options.

---

# Consent form

The whole survey will take approximately 10 to 15 minutes to complete. Your participation is voluntary and you may stop the survey at any time.

If you would like to participate, please answer the following questions:

I am voluntarily participating in this survey

- Yes
- No

I have read and understand the above information

- Yes
- No

---

Are you planning to relocate in the next five years?

- Yes
- No

If not, please note why have you signed up in the housing que.

(open text response)

---

Before we go on, please select which types of housing you are interested in:

- House
- Apartment
- Open to both options

(For this example, I'm using the response here to screen out respondents - I'm only interested in people who choose "Red", so if you choose "Blue" you'll be screened out. Usually you would not tell respondents ahead of time how they will be screened - I'm just putting an explanation here since this whole survey is for demonstration purposes)